# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
x = np.random.random((3,3,3))
print(x) 

[[[0.737984   0.99530392 0.97309263]
  [0.48748687 0.33880373 0.32159412]
  [0.97130696 0.15396756 0.73488319]]

 [[0.32886685 0.98873149 0.91898559]
  [0.53386669 0.72306467 0.26433671]
  [0.71117835 0.68829871 0.53158805]]

 [[0.65528523 0.72273221 0.10463842]
  [0.45811686 0.71115776 0.92692995]
  [0.88996188 0.02200366 0.69969349]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [22]:
d = np.diag(1+np.arange(4), k = -1)
print (diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [35]:
x=np.array([[0,1], [1,0]])
x1=np.tile(x,(4,4))
x1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [36]:

rm = np.random.random((5,5))
rm_max, rm_min = rm.max(), rm.min()
rm= (rm-rm_min)/(rm_max-rm_min)
print (rm)

[[0.85854522 0.56499623 0.36087161 0.4846514  0.30782472]
 [0.29698228 0.12079242 0.37590931 0.63159409 1.        ]
 [0.82318745 0.29599459 0.94368307 0.         0.95927503]
 [0.4817806  0.52025419 0.11088437 0.91034184 0.90121708]
 [0.98943291 0.58286008 0.75954988 0.34762704 0.77650893]]


# 5.  How to find common values between two arrays?

In [37]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [85]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [82]:
array1 = np.random.randint(5, size=5)
print("Array1: ",array1)
array2 = np.random.randint(5, size=5)
print("Array2: ",array2)
array_equal = np.allclose(array1, array2)
if(array_equal=='False'):
    print("Two arrays are not equal")
else:
    print("Two arrays are not equal")    

Array1:  [0 1 2 2 4]
Array2:  [2 4 1 4 2]
Two arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [78]:
x = np.random.randint(1,10,10)
print(x)
x[x.argmax()] = 0
print(x)

[8 3 9 3 9 4 2 1 4 4]
[8 3 0 3 9 4 2 1 4 4]


# 9. How to print all the values of an array?

In [75]:
a = np.random.randint(1,5,(3,3))
print(a)

[[2 1 2]
 [4 4 3]
 [1 1 3]]


# 10.Subtract the mean of each row of a matrix

In [70]:
X = np.random.randint(1,5,(3,3))
print(X)
Y = X - X.mean()
print("\n",Y)

[[2 2 2]
 [3 4 4]
 [2 4 4]]

 [[-1. -1. -1.]
 [ 0.  1.  1.]
 [-1.  1.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [91]:
arr1= np.random.randint(0,5,10)
print(arr1)
arr2= np.random.randint(0,8,10)
print (arr2)

[3 1 2 4 4 2 3 3 4 2]
[1 2 3 5 4 4 3 1 2 7]


In [93]:
arr1 += np.bincount(arr2, minlength=len(arr1))
print (arr1)

[3 5 6 8 8 4 3 5 4 2]


# 12.How to get the diagonal of a dot product?

In [62]:
x = np.random.randint(0,10,(3,3))
print(x)
print()
y = np.random.randint(0,10,(3,3))
print(y)
print()
print("Diagonal of a dot product :",np.diag(np.dot(x,y)))

[[4 5 8]
 [2 9 0]
 [9 6 1]]

[[3 2 7]
 [5 4 8]
 [0 9 7]]

Diagonal of a dot product : [ 37  40 118]


# 13.How to find the most frequent value in an array?

In [58]:
x = np.random.randint(1,6,5)
print (x)
print('Most frequent:', np.bincount(x).argmax())

[4 4 1 4 2]
Most frequent: 4


# 14.How to get the n largest values of an array

In [47]:
x = np.array([2,3,5,48,9,2,6,58,2])
n = 2
print (n,"Largest values are :" , x[np.argsort(x)[-n:]])

2 Largest values are : [48 58]
[48 58]


# 15.How to create a record array from a regular array?

In [38]:
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
ra = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

print (ra)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
